import torch
import torchvision.transforms as transforms
import numpy as np
import matplotlib.pyplot as plt
import warnings
import os
from PIL import Image
from tqdm import tqdm
from efficientnet_pytorch import EfficientNet

warnings.filterwarnings('ignore')

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
print(f'Using {device} for inference')
utils = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_convnets_processing_utils')

root_dir = '/home/oyku/texas/test'
ground_truth_file = '/home/oyku/texas/test_ground_truth.txt'
num_test_files = 150000  # Number of test files to use

# Read the ground truth labels from the text file
ground_truth_labels = []

with open(ground_truth_file, 'r') as file:
    for i in range(num_test_files):
        label = file.readline().strip()
        if not label:
            break
        ground_truth_labels.append(int(label))

mapping_dict = {
    
'french fries, french-fried potatoes, fries, chips':'1',
'mashed potato':'2',
'black olive, ripe olive':'3',
'face powder':'4',
'crab apple, crabapple':'5',
'Granny Smith':'6',
'strawberry':'7',
'blueberry':'8',
'cranberry':'9',
'currant':'10	',
'blackberry':'11	',
'raspberry':'12	',
'persimmon':'13	',
'mulberry':'14	',
'orange':'15	',
'kumquat':'16	',
'lemon':'17	',
'grapefruit':'18	',
'plum':'19	',
'fig':'20	',
'pineapple, ananas':'21	',
'banana':'22	',
'jackfruit, jak, jack':'23	',
'cherry':'24	',
'grape':'25	',
'custard apple':'26	',
'durian':'27	',
'mango':'28	',
'elderberry':'29	',
'guava':'30	',
'litchi, litchi nut, litchee, lichi, leechee, lichee, lychee':'31	',
'pomegranate':'32	',
'quince':'33	',
'kidney bean':'34	',
'soy, soybean, soya, soya bean':'35	',
'green pea, garden pea':'36	',
'chickpea, garbanzo':'37	',
'chard, Swiss chard, spinach beet, leaf beet':'38	',
'lettuce':'39	',
'cress':'40	',
'spinach':'41	',
'bell pepper':'42	',
'pimento, pimiento':'43	',
'jalapeno, jalapeno pepper':'44	',
'cherry tomato':'45	',
'parsnip':'46	',
'turnip':'47	',
'mustard, mustard greens, leaf mustard, Indian mustard':'48	',
'bok choy, bok choi':'49	',
'head cabbage':'50	',
'broccoli':'51	',
'cauliflower':'52	',
'brussels sprouts':'53	',
'zucchini, courgette':'54	',
'spaghetti squash':'55	',
'acorn squash':'56	',
'butternut squash':'57	',
'cucumber, cuke':'58	',
'artichoke, globe artichoke':'59	',
'asparagus':'60	',
'green onion, spring onion, scallion':'61	',
'shallot':'62	',
'leek':'63	',
'cardoon':'64	',
'celery':'65	',
'mushroom':'66	',
'pumpkin':'67	',
'cliff, drop, drop-off':'68	',
'lunar crater':'69	',
'valley, vale':'70	',
'alp':'71	',
'volcano':'72	',
'promontory, headland, head, foreland':'73	',
'sandbar, sand bar':'74	',
'dune, sand dune':'75	',
'coral reef':'76	',
'lakeside, lakeshore':'77	',
'seashore, coast, seacoast, sea-coast':'78	',
'geyser':'79	',
'bakery, bakeshop, bakehouse':'80	',
'juniper berry':'81	',
'gourd':'82	',
'acorn':'83	',
'olive':'84	',
'hip, rose hip, rosehip':'85	',
'ear, spike, capitulum':'86	',
'pumpkin seed':'87	',
'sunflower seed':'88	',
'coffee bean, coffee berry, coffee':'89	',
'rapeseed':'90	',
'corn':'91	',
'buckeye, horse chestnut, conker':'92	',
'bean':'93	',
'peanut, earthnut, goober, goober pea, groundnut, monkey nut':'94	',
'walnut':'95	',
'cashew, cashew nut':'96	',
'chestnut':'97	',
'hazelnut, filbert, cobnut, cob':'98	',
'coconut, cocoanut':'99	',
'pecan':'100	',
'pistachio, pistachio nut':'101	',
'lentil':'102	',
'pea':'103	',
'peanut':'104	',
'okra':'105	',
'sunflower, helianthus':'106	',
'lesser celandine, pilewort, Ranunculus ficaria':'107	',
'wood anemone, Anemone nemorosa':'108	',
'blue columbine, Aquilegia caerulea, Aquilegia scopulorum calcarea':'109	',
'delphinium':'110	',
'nigella':'111	',
'calla lily, calla, arum lily, Zantedeschia aethiopica':'112	',
'sandwort':'113	',
'pink, garden pink':'114	',
'baby''s breath, babies''-breath, Gypsophila paniculata':'115	',
'ice plant, icicle plant, Mesembryanthemum crystallinum':'116	',
'globe amaranth, bachelor''s button, Gomphrena globosa':'117	',
'four o''clock':'118	',
'Virginia spring beauty, Claytonia virginica':'119	',
'wallflower':'120	',
'damask violet, Dame''s violet, sweet rocket, Hesperis matronalis':'121	',
'candytuft':'122	',
'Iceland poppy, Papaver alpinum':'123	',
'prickly poppy, Papaver argemone':'124	',
'oriental poppy, Papaver orientale':'125	',
'celandine, greater celandine, swallowwort, swallow wort, Chelidonium majus':'126	',
'blue poppy, Meconopsis betonicifolia':'127	',
'Welsh poppy, Meconopsis cambrica':'128	',
'celandine poppy, wood poppy, Stylophorum diphyllum':'129	',
'corydalis':'130	',
'pearly everlasting, cottonweed, Anaphalis margaritacea':'131	',
'strawflower, golden everlasting, yellow paper daisy, Helichrysum bracteatum':'132	',
'yellow chamomile, golden marguerite, dyers'' chamomile, Anthemis tinctoria':'133	',
'dusty miller, silver-lace, silver lace, Tanacetum ptarmiciflorum, Chrysanthemum ptarmiciflorum':'134	',
'tansy, golden buttons, scented fern, Tanacetum vulgare':'135	',
'daisy':'136	',
'common marigold, pot marigold, ruddles, Scotch marigold, Calendula officinalis':'137	',
'China aster, Callistephus chinensis':'138	',
'cornflower, bachelor''s button, bluebottle, Centaurea cyanus':'139	',
'chrysanthemum':'140	',
'mistflower, mist-flower, ageratum, Conoclinium coelestinum, Eupatorium coelestinum':'141	',
'cosmos, cosmea':'142	',
'dahlia, Dahlia pinnata':'143	',
'coneflower':'144	',
'blue daisy, blue marguerite, Felicia amelloides':'145	',
'gazania':'146	',
'African daisy':'147	',
'male orchis, early purple orchid, Orchis mascula':'148	',
'butterfly orchid, butterfly orchis, Orchis papilionaceae':'149	',
'aerides':'150	',
'brassavola':'151	',
'spider orchid, Brassia lawrenceana':'152	',
'grass pink, Calopogon pulchellum, Calopogon tuberosum':'153	',
'calypso, fairy-slipper, Calypso bulbosa':'154	',
'cattleya':'155	',
'red helleborine, Cephalanthera rubra':'156	',
'coelogyne':'157	',
'cymbid, cymbidium':'158	',
'lady''s slipper, lady-slipper, ladies'' slipper, slipper orchid':'159	',
'marsh orchid':'160	',
'dendrobium':'161	',
'disa':'162	',
'helleborine':'163	',
'fragrant orchid, Gymnadenia conopsea':'164	',
'fringed orchis, fringed orchid':'165	',
'lizard orchid, Himantoglossum hircinum':'166	',
'laelia':'167	',
'masdevallia':'168	',
'odontoglossum':'169	',
'oncidium, dancing lady orchid, butterfly plant, butterfly orchid':'170	',
'bee orchid, Ophrys apifera':'171	',
'fly orchid, Ophrys insectifera, Ophrys muscifera':'172	',
'spider orchid':'173	',
'phaius':'174	',
'moth orchid, moth plant':'175	',
'ladies'' tresses, lady''s tresses':'176	',
'stanhopea':'177	',
'stelis':'178	',
'vanda':'179	',
'cyclamen, Cyclamen purpurascens':'180	',
'centaury':'181	',
'gentian':'182	',
'begonia':'183	',
'commelina':'184	',
'scabious, scabiosa':'185	',
'achimenes, hot water plant':'186	',
'African violet, Saintpaulia ionantha':'187	',
'streptocarpus':'188	',
'scorpionweed, scorpion weed, phacelia':'189	',
'calceolaria, slipperwort':'190	',
'toadflax, butter-and-eggs, wild snapdragon, devil''s flax, Linaria vulgaris':'191	',
'veronica, speedwell':'192	',
'bonsai':'193	',
'star anise, Chinese anise, Illicium verum':'194	',
'wattle':'195	',
'huisache, cassie, mimosa bush, sweet wattle, sweet acacia, scented wattle, flame tree, Acacia farnesiana':'196	',
'silk tree, Albizia julibrissin, Albizzia julibrissin':'197	',
'rain tree, saman, monkeypod, monkey pod, zaman, zamang, Albizia saman':'198	',
'dita, dita bark, devil tree, Alstonia scholaris':'199	',
'pandanus, screw pine':'200	',
'linden, linden tree, basswood, lime, lime tree':'201	',
'American beech, white beech, red beech, Fagus grandifolia, Fagus americana':'202	',
'New Zealand beech':'203	',
'live oak':'204	',
'shingle oak, laurel oak, Quercus imbricaria':'205	',
'pin oak, swamp oak, Quercus palustris':'206	',
'cork oak, Quercus suber':'207	',
'yellow birch, Betula alleghaniensis, Betula leutea':'208	',
'American white birch, paper birch, paperbark birch, canoe birch, Betula cordifolia, Betula papyrifera':'209	',
'downy birch, white birch, Betula pubescens':'210	',
'alder, alder tree':'211	',
'fringe tree':'212	',
'European ash, common European ash, Fraxinus excelsior':'213	',
'fig, common fig, common fig tree, Ficus carica':'214	',
'witch elm, wych elm, Ulmus glabra':'215	',
'Dutch elm, Ulmus hollandica':'216	',
'cabbage tree, grass tree, Cordyline australis':'217	',
'golden shower tree, drumstick tree, purging cassia, pudding pipe tree, canafistola, canafistula, Cassia fistula':'218	',
'honey locust, Gleditsia triacanthos':'219	',
'Kentucky coffee tree, bonduc, chicot, Gymnocladus dioica':'220	',
'Brazilian rosewood, caviuna wood, jacaranda, Dalbergia nigra':'221	',
'logwood, logwood tree, campeachy, bloodwood tree, Haematoxylum campechianum':'222	',
'coral tree, erythrina':'223	',
'Japanese pagoda tree, Chinese scholartree, Chinese scholar tree, Sophora japonica, Sophora sinensis':'224	',
'kowhai, Sophora tetraptera':'225	',
'palm, palm tree':'226	',
'Arabian coffee, Coffea arabica':'227	',
'cork tree, Phellodendron amurense':'228	',
'weeping willow, Babylonian weeping willow, Salix babylonica':'229	',
'pussy willow, Salix discolor':'230	',
'goat willow, florist''s willow, pussy willow, Salix caprea':'231	',
'China tree, false dogwood, jaboncillo, chinaberry, Sapindus saponaria':'232	',
'pepper tree, molle, Peruvian mastic tree, Schinus molle':'233	',
'balata, balata tree, beefwood, bully tree, Manilkara bidentata':'234	',
'teak, Tectona grandis':'235	',
'ginkgo, gingko, maidenhair tree, Ginkgo biloba':'236	',
'pine, pine tree, true pine':'237	',
'ilang-ilang, ylang-ylang, Cananga odorata':'238	',
'laurel':'239	',
'magnolia':'240	',
'tulip tree, tulip poplar, yellow poplar, canary whitewood, Liriodendron tulipifera':'241	',
'baobab, monkey-bread tree, Adansonia digitata':'242	',
'kapok, ceiba tree, silk-cotton tree, white silk-cotton tree, Bombay ceiba, God tree, Ceiba pentandra':'243	',
'red beech, brown oak, booyong, crow"s foot, stave wood, silky elm, Heritiera trifoliolata, Terrietia trifoliolata':'244	',
'cacao, cacao tree, chocolate tree, Theobroma cacao':'245	',
'sorrel tree, sourwood, titi, Oxydendrum arboreum':'246	',
'iron tree, iron-tree, ironwood, ironwood tree':'247	',
'mangrove, Rhizophora mangle':'248	',
'paper mulberry, Broussonetia papyrifera':'249	',
'Judas tree, love tree, Circis siliquastrum':'250	',
'redbud, Cercis canadensis':'251	',
'mountain ash':'252	',
'ailanthus':'253	',
'silver maple, Acer saccharinum':'254	',
'Oregon maple, big-leaf maple, Acer macrophyllum':'255	',
'sycamore, great maple, scottish maple, Acer pseudoplatanus':'256	',
'box elder, ash-leaved maple, Acer negundo':'257	',
'Japanese maple, full moon maple, Acer japonicum':'258	',
'holly':'259	',
'dogwood, dogwood tree, cornel':'260	',
'truffle, earthnut, earth-ball':'261	',
'shiitake, shiitake mushroom, Chinese black mushroom, golden oak mushroom, Oriental black mushroom, Lentinus edodes':'262	',
'lichen':'263	',
'hen-of-the-woods, hen of the woods, Polyporus frondosus, Grifola frondosa':'264	',
'jelly fungus':'265	',
'dead-man''s-fingers, dead-men''s-fingers, Xylaria polymorpha':'266	',
'earthstar':'267	',
'coral fungus':'268	',
'stinkhorn, carrion fungus':'269	',
'puffball, true puffball':'270	',
'gyromitra':'271	',
'bolete':'272	',
'polypore, pore fungus, pore mushroom':'273	',
'gill fungus':'274	',
'morel':'275	',
'agaric':'276	',
'trilobite':'277	',
'harvestman, daddy longlegs, Phalangium opilio':'278	',
'scorpion':'279	',
'black and gold garden spider, Argiope aurantia':'280	',
'barn spider, Araneus cavaticus':'281	',
'garden spider, Aranea diademata':'282	',
'black widow, Latrodectus mactans':'283	',
'tarantula':'284	',
'wolf spider, hunting spider':'285	',
'tick':'286	',
'mite':'287	',
'centipede':'288	',
'millipede, millepede, milliped':'289	',
'horseshoe crab, king crab, Limulus polyphemus, Xiphosurus polyphemus':'290	',
'isopod':'291	',
'Dungeness crab, Cancer magister':'292	',
'rock crab, Cancer irroratus':'293	',
'fiddler crab':'294	',
'king crab, Alaska crab, Alaskan king crab, Alaska king crab, Paralithodes camtschatica':'295	',
'American lobster, Northern lobster, Maine lobster, Homarus americanus':'296	',
'spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish':'297	',
'crayfish, crawfish, crawdad, crawdaddy':'298	',
'hermit crab':'299	',
'shrimp':'300	',
'barnacle, cirriped, cirripede':'301	',
'tiger beetle':'302	',
'ladybug, ladybeetle, lady beetle, ladybird, ladybird beetle':'303	',
'ground beetle, carabid beetle':'304	',
'long-horned beetle, longicorn, longicorn beetle':'305	',
'leaf beetle, chrysomelid':'306	',
'weevil':'307	',
'fly':'308	',
'mosquito':'309	',
'ant, emmet, pismire':'310	',
'bee':'311	',
'grasshopper, hopper':'312	',
'cricket':'313	',
'walking stick, walkingstick, stick insect':'314	',
'cockroach, roach':'315	',
'mantis, mantid':'316	',
'cicada, cicala':'317	',
'leafhopper':'318	',
'mayfly, dayfly, shadfly':'319	',
'lacewing, lacewing fly':'320	',
'dragonfly, darning needle, devil"s darning needle, sewing needle, snake feeder, snake doctor, mosquito hawk,skeeter hawk':'321	',
'damselfly':'322	',
'nymphalid, nymphalid butterfly, brush-footed butterfly, four-footed butterfly':'323	',
'ringlet, ringlet butterfly':'324	',
'monarch, monarch butterfly, milkweed butterfly, Danaus plexippus':'325	',
'cabbage butterfly':'326	',
'sulphur butterfly, sulfur butterfly':'327	',
'lycaenid, lycaenid butterfly':'328	',
'moth':'329	',
'polyp':'330	',
'jellyfish':'331	',
'sea anemone, anemone':'332	',
'coral':'333	',
'flatworm, platyhelminth':'334	',
'nematode, nematode worm, roundworm':'335	',
'earthworm, angleworm, fishworm, fishing worm, wiggler, nightwalker, nightcrawler, crawler, dew worm, red worm':'336	',
'conch':'337	',
'snail':'338	',
'slug':'339	',
'sea slug, nudibranch':'340	',
'cowrie, cowry':'341	',
'chiton, coat-of-mail shell, sea cradle, polyplacophore':'342	',
'clam':'343	',
'mussel':'344	',
'chambered nautilus, pearly nautilus, nautilus':'345	',
'starfish, sea star':'346	',
'sea urchin':'347	',
'sea cucumber, holothurian':'348	',
'Egyptian cat':'349	',
'Persian cat':'350	',
'tiger cat':'351	',
'Siamese cat, Siamese':'352	',
'tabby, tabby cat':'353	',
'vizsla, Hungarian pointer':'354	',
'English setter':'355	',
'Gordon setter':'356	',
'Irish setter, red setter':'357	',
'Brittany spaniel':'358	',
'golden retriever':'359	',
'flat-coated retriever':'360	',
'Australian terrier':'361	',
'Yorkshire terrier':'362	',
'Staffordshire bullterrier, Staffordshire bull terrier':'363	',
'Scottish deerhound, deerhound':'364	',
'greyhound':'365	',
'Rhodesian ridgeback':'366	',
'dalmatian, coach dog, carriage dog':'367	',
'corgi, Welsh corgi':'368	',
'Newfoundland, Newfoundland dog':'369	',
'miniature poodle':'370	',
'standard poodle':'371	',
'basenji':'372	',
'griffon, Brussels griffon, Belgian griffon':'373	',
'Great Dane':'374	',
'Bouvier des Flandres, Bouviers des Flandres':'375	',
'Border collie':'376	',
'German shepherd, German shepherd dog, German police dog, alsatian':'377	',
'Doberman, Doberman pinscher':'378	',
'boxer':'379	',
'Eskimo dog, husky':'380	',
'Saint Bernard, St Bernard':'381	',
'Tibetan mastiff':'382	',
'Pekinese, Pekingese, Peke':'383	',
'Chihuahua':'384	',
'black grouse':'385	',
'ptarmigan':'386	',
'ruffed grouse, partridge, Bonasa umbellus':'387	',
'prairie chicken, prairie grouse, prairie fowl':'388	',
'pheasant':'389	',
'quail':'390	',
'partridge':'391	',
'hare':'392	',
'Angora, Angora rabbit':'393	',
'wood rabbit, cottontail, cottontail rabbit':'394	',
'indri, indris, Indri indri, Indri brevicaudatus':'395	',
'Madagascar cat, ring-tailed lemur, Lemur catta':'396	',
'orangutan, orang, orangutang, Pongo pygmaeus':'397	',
'chimpanzee, chimp, Pan troglodytes':'398	',
'gorilla, Gorilla gorilla':'399	',
'siamang, Hylobates syndactylus, Symphalangus syndactylus':'400	',
'gibbon, Hylobates lar':'401	',
'titi, titi monkey':'402	',
'squirrel monkey, Saimiri sciureus':'403	',
'spider monkey, Ateles geoffroyi':'404	',
'howler monkey, howler':'405	',
'marmoset':'406	',
'colobus, colobus monkey':'407	',
'guenon, guenon monkey':'408	',
'proboscis monkey, Nasalis larvatus':'409	',
'patas, hussar monkey, Erythrocebus patas':'410	',
'baboon':'411	',
'macaque':'412	',
'langur':'413	',
'African elephant, Loxodonta africana':'414	',
'Indian elephant, Elephas maximus':'415	',
'brown bear, bruin, Ursus arctos':'416	',
'ice bear, polar bear, Ursus Maritimus, Thalarctos maritimus':'417	',
'American black bear, black bear, Ursus americanus, Euarctos americanus':'418	',
'sloth bear, Melursus ursinus, Ursus ursinus':'419	',
'badger':'420	',
'mink':'421	',
'black-footed ferret, ferret, Mustela nigripes':'422	',
'skunk, polecat, wood pussy':'423	',
'weasel':'424	',
'polecat, fitch, foulmart, foumart, Mustela putorius':'425	',
'otter':'426	',
'lesser panda, red panda, panda, bear cat, cat bear, Ailurus fulgens':'427	',
'giant panda, panda, panda bear, coon bear, Ailuropoda melanoleuca':'428	',
'raccoon, racoon':'429	',
'meerkat, mierkat':'430	',
'mongoose':'431	',
'dingo, warrigal, warragal, Canis dingo':'432	',
'African hunting dog, hyena dog, Cape hunting dog, Lycaon pictus':'433	',
'hyena, hyaena':'434	',
'kit fox, Vulpes macrotis':'435	',
'red fox, Vulpes vulpes':'436	',
'grey fox, gray fox, Urocyon cinereoargenteus':'437	',
'Arctic fox, white fox, Alopex lagopus':'438	',
'red wolf, maned wolf, Canis rufus, Canis niger':'439	',
'coyote, prairie wolf, brush wolf, Canis latrans':'440	',
'white wolf, Arctic wolf, Canis lupus tundrarum':'441	',
'timber wolf, grey wolf, gray wolf, Canis lupus':'442	',
'cougar, puma, catamount, mountain lion, painter, panther, Felis concolor':'443	',
'lynx, catamount':'444	',
'jaguar, panther, Panthera onca, Felis onca':'445	',
'tiger, Panthera tigris':'446	',
'leopard, Panthera pardus':'447	',
'snow leopard, ounce, Panthera uncia':'448	',
'lion, king of beasts, Panthera leo':'449	',
'cheetah, chetah, Acinonyx jubatus':'450	',
'loggerhead, loggerhead turtle, Caretta caretta':'451	',
'leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea':'452	',
'mud turtle':'453	',
'terrapin':'454	',
'box turtle, box tortoise':'455	',
'banded gecko':'456	',
'common iguana, iguana, Iguana iguana':'457	',
'American chameleon, anole, Anolis carolinensis':'458	',
'whiptail, whiptail lizard':'459	',
'agama':'460	',
'frilled lizard, Chlamydosaurus kingi':'461	',
'alligator lizard':'462	',
'Gila monster, Heloderma suspectum':'463	',
'green lizard, Lacerta viridis':'464	',
'African chameleon, Chamaeleo chamaeleon':'465	',
'Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis':'466	',
'thunder snake, worm snake, Carphophis amoenus':'467	',
'ringneck snake, ring-necked snake, ring snake':'468	',
'hognose snake, puff adder, sand viper':'469	',
'green snake, grass snake':'470	',
'king snake, kingsnake':'471	',
'garter snake, grass snake':'472	',
'water snake':'473	',
'vine snake':'474	',
'night snake, Hypsiglena torquata':'475	',
'boa constrictor, Constrictor constrictor':'476	',
'Indian cobra, Naja naja':'477	',
'green mamba':'478	',
'horned viper, cerastes, sand viper, horned asp, Cerastes cornutus':'479	',
'wood-frog, wood frog, Rana sylvatica':'480	',
'leopard frog, spring frog, Rana pipiens':'481	',
'bullfrog, Rana catesbeiana':'482	',
'tree frog, tree-frog':'483	',
'tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui':'484	',
'European fire salamander, Salamandra salamandra':'485	',
'common newt, Triturus vulgaris':'486	',
'axolotl, mud puppy, Ambystoma mexicanum':'487	',
'great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias':'488	',
'tiger shark, Galeocerdo cuvieri':'489	',
'hammerhead, hammerhead shark':'490	',
'electric ray, crampfish, numbfish, torpedo':'491	',
'stingray':'492	',
'barracouta, snoek':'493	',
'coho, cohoe, coho salmon, blue jack, silver salmon, Oncorhynchus kisutch':'494	',
'rainbow trout, Salmo gairdneri':'495	',
'striped bass, striper, Roccus saxatilis, rockfish':'496	',
'sturgeon':'497	',
'gar, garfish, garpike, billfish, Lepisosteus osseus':'498	',
'euphonium':'499	',
'accordion, piano accordion, squeeze box':'500	',
'grand piano, grand':'501	',
'upright, upright piano':'502	',
'chime, bell, gong':'503	',
'drum, membranophone, tympan':'504	',
'gong, tam-tam':'505	',
'maraca':'506	',
'marimba, xylophone':'507	',
'banjo':'508	',
'cello, violoncello':'509	',
'violin, fiddle':'510	',
'harp':'511	',
'acoustic guitar':'512	',
'electric guitar':'513	',
'cornet, horn, trumpet, trump':'514	',
'French horn, horn':'515	',
'trombone':'516	',
'harmonica, mouth organ, harp, mouth harp':'517	',
'organ pipe, pipe, pipework':'518	',
'panpipe, pandean pipe, syrinx':'519	',
'bassoon':'520	',
'oboe, hautboy, hautbois':'521	',
'sax, saxophone':'522	',
'flute, transverse flute':'523	',
'bell':'524	',
'whistle':'525	',
'paintbrush':'526	',
'hand blower, blow dryer, blow drier, hair dryer, hair drier':'527	',
'oxygen mask':'528	',
'snorkel':'529	',
'earphone, earpiece, headphone, phone':'530	',
'loudspeaker, speaker, speaker unit, loudspeaker system, speaker system':'531	',
'microphone, mike':'532	',
'mouse, computer mouse':'533	',
'scanner, digital scanner, image scanner':'534	',
'trackball':'535	',
'electric fan, blower':'536	',
'guillotine':'537	',
'barometer':'538	',
'rule, ruler':'539	',
'odometer, hodometer, mileometer, milometer':'540	',
'scale, weighing machine':'541	',
'thermometer':'542	',
'watch, ticker':'543	',
'analog clock':'544	',
'digital clock':'545	',
'pendulum clock':'546	',
'hourglass':'547	',
'sundial':'548	',
'stethoscope':'549	',
'syringe':'550	',
'binoculars, field glasses, opera glasses':'551	',
'projector':'552	',
'hand glass, simple microscope, magnifying glass':'553	',
'optical telescope':'554	',
'radio telescope, radio reflector':'555	',
'missile':'556	',
'bow':'557	',
'cannon':'558	',
'machine gun':'559	',
'revolver, six-gun, six-shooter':'560	',
'rifle':'561	',
'sword, blade, brand, steel':'562	',
'computer keyboard, keypad':'563	',
'crane':'564	',
'lighter, light, igniter, ignitor':'565	',
'chain saw, chainsaw':'566	',
'circular saw, buzz saw':'567	',
'abacus':'568	',
'hand calculator, pocket calculator':'569	',
'cash machine, cash dispenser, automated teller machine, automatic teller machine, automated teller, automatic teller, ATM':'570	',
'desktop computer':'571	',
'laptop, laptop computer':'572	',
'hand-held computer, hand-held microcomputer':'573	',
'web site, website, internet site, site':'574	',
'harvester, reaper':'575	',
'thresher, thrasher, threshing machine':'576	',
'printer':'577	',
'slot, one-armed bandit':'578	',
'vending machine':'579	',
'sewing machine':'580	',
'joystick':'581	',
'gas pump, gasoline pump, petrol pump, island dispenser':'582	',
'carousel, carrousel, merry-go-round, roundabout, whirligig':'583	',
'Ferris wheel':'584	',
'roller coaster, big dipper, chute-the-chute':'585	',
'hard disc, hard disk, fixed disk':'586	',
'flash memory':'587	',
'car mirror':'588	',
'solar dish, solar collector, solar furnace':'589	',
'remote control, remote':'590	',
'buckle':'591	',
'button':'592	',
'hair slide':'593	',
'paper clip, paperclip, gem clip':'594	',
'knot':'595	',
'combination lock':'596	',
'padlock':'597	',
'nail':'598	',
'pin':'599	',
'screw':'600	',
'seat belt, seatbelt':'601	',
'shredder':'602	',
'candle, taper, wax light':'603	',
'flash, photoflash, flash lamp, flashgun, flashbulb, flash bulb':'604	',
'Chinese lantern':'605	',
'jack-o''-lantern':'606	',
'mousetrap':'607	',
'spider web, spider''s web':'608	',
'comb':'609	',
'ax, axe':'610	',
'chisel':'611	',
'cleaver, meat cleaver, chopper':'612	',
'pocketknife, pocket knife':'613	',
'plane, carpenter''s plane, woodworking plane':'614	',
'safety razor':'615	',
'shaver, electric shaver, electric razor':'616	',
'straight razor':'617	',
'scissors, pair of scissors':'618	',
'drill':'619	',
'lawn mower, mower':'620	',
'hammer':'621	',
'cap opener':'622	',
'corkscrew, bottle screw':'623	',
'can opener, tin opener':'624	',
'plunger, plumber''s helper':'625	',
'saw':'626	',
'screwdriver':'627	',
'shovel':'628	',
'trowel':'629	',
'adjustable wrench, adjustable spanner':'630	',
'plow, plough':'631	',
'rake':'632	',
'ceramic ware':'633	',
'frying pan, frypan, skillet':'634	',
'wok':'635	',
'caldron, cauldron':'636	',
'coffeepot':'637	',
'teapot':'638	',
'spatula':'639	',
'eggbeater, eggwhisk':'640	',
'swab, swob, mop':'641	',
'broom':'642	',
'toothbrush':'643	',
'rubber eraser, rubber, pencil eraser':'644	',
'pencil sharpener':'645	',
'fishing rod, fishing pole':'646	',
'quill, quill pen':'647	',
'ballpoint, ballpoint pen, ballpen, Biro':'648	',
'fountain pen':'649	',
'pencil':'650	',
'needle':'651	',
'drumstick':'652	',
'crutch':'653	',
'flagpole, flagstaff':'654	',
'matchstick':'655	',
'bicycle-built-for-two, tandem bicycle, tandem':'656	',
'mountain bike, all-terrain bike, off-roader':'657	',
'freight car':'658	',
'passenger car, coach, carriage':'659	',
'barrow, garden cart, lawn cart, wheelbarrow':'660	',
'shopping cart':'661	',
'motor scooter, scooter':'662	',
'tank, army tank, armored combat vehicle, armoured combat vehicle':'663	',
'forklift':'664	',
'electric locomotive':'665	',
'steam locomotive':'666	',
'amphibian, amphibious vehicle':'667	',
'ambulance':'668	',
'beach wagon, station wagon, wagon, estate car, beach waggon, station waggon, waggon':'669	',
'cab, hack, taxi, taxicab':'670	',
'convertible':'671	',
'jeep, landrover':'672	',
'limousine, limo':'673	',
'minivan':'674	',
'Model T':'675	',
'racer, race car, racing car':'676	',
'go-kart':'677	',
'golfcart, golf cart':'678	',
'moped':'679	',
'snowplow, snowplough':'680	',
'fire engine, fire truck':'681	',
'garbage truck, dustcart':'682	',
'pickup, pickup truck':'683	',
'trailer truck, tractor trailer, trucking rig, rig, articulated lorry, semi':'684	',
'police van, police wagon, paddy wagon, patrol wagon, wagon, black Maria':'685	',
'recreational vehicle, RV, R.V.':'686	',
'half track':'687	',
'snowmobile':'688	',
'tractor':'689	',
'tricycle, trike, velocipede':'690	',
'unicycle, monocycle':'691	',
'horse cart, horse-cart':'692	',
'jinrikisha, ricksha, rickshaw':'693	',
'oxcart':'694	',
'covered wagon, Conestoga wagon, Conestoga, prairie wagon, prairie schooner':'695	',
'hamper':'696	',
'shopping basket':'697	',
'thimble':'698	',
'mailbag, postbag':'699	',
'backpack, back pack, knapsack, packsack, rucksack, haversack':'700	',
'sleeping bag':'701	',
'ashcan, trash can, garbage can, wastebin, ash bin, ash-bin, ashbin, dustbin, trash barrel, trash bin':'702	',
'cocktail shaker':'703	',
'saltshaker, salt shaker':'704	',
'washbasin, handbasin, washbowl, lavabo, wash-hand basin':'705	',
'vase':'706	',
'beaker':'707	',
'bucket, pail':'708	',
'mortar':'709	',
'beer bottle':'710	',
'ink bottle, inkpot':'711	',
'canteen':'712	',
'hipflask, pocket flask':'713	',
'water tower':'714	',
'rain barrel':'715	',
'bathtub, bathing tub, bath, tub':'716	',
'ladle':'717	',
'barrel, cask':'718	',
'pitcher, ewer':'719	',
'mug':'720	',
'envelope':'721	',
'beer glass':'722	',
'goblet':'723	',
'carton':'724	',
'chest':'725	',
'safe':'726	',
'crate':'727	',
'mailbox, letter box':'728	',
'measuring cup':'729	',
'wallet, billfold, notecase, pocketbook':'730	',
'bag, traveling bag, travelling bag, grip, suitcase':'731	',
'golf ball':'732	',
'baseball':'733	',
'balance beam, beam':'734	',
'horizontal bar, high bar':'735	',
'parallel bars, bars':'736	',
'basketball':'737	',
'croquet ball':'738	',
'barbell':'739	',
'dumbbell':'740	',
'in-line skate':'741	',
'ice skate':'742	',
'pool table, billiard table, snooker table':'743	',
'crossword puzzle, crossword':'744	',
'jigsaw puzzle':'745	',
'bowling pin, pin':'746	',
'chessman, chess piece':'747	',
'soccer ball':'748	',
'pool ball':'749	',
'rugby ball':'750	',
'volleyball':'751	',
'tennis ball':'752	',
'point-and-shoot camera':'753	',
'Polaroid camera, Polaroid Land camera':'754	',
'reflex camera':'755	',
'carpenter''s kit, tool kit':'756	',
'drilling platform, offshore rig':'757	',
'iPod':'758	',
'oscilloscope, scope, cathode-ray oscilloscope, CRO':'759	',
'camcorder':'760	',
'monitor':'761	',
'cassette player':'762	',
'cellular telephone, cellular phone, cellphone, cell, mobile phone':'763	',
'pay-phone, pay-station':'764	',
'dial telephone, dial phone':'765	',
'tape player':'766	',
'CD player':'767	',
'photocopier':'768	',
'metronome':'769	',
'parachute, chute':'770	',
'brick':'771	',
'lipstick, lip rouge':'772	',
'nail polish, nail enamel, nail varnish':'773	',
'lotion':'774	',
'hair spray':'775	',
'bumper car, Dodgem':'776	',
'airliner':'777	',
'warplane, military plane':'778	',
'airship, dirigible':'779	',
'balloon':'780	',
'fireboat':'781	',
'gondola':'782	',
'speedboat':'783	',
'lifeboat':'784	',
'canoe':'785	',
'schooner':'786	',
'catamaran':'787	',
'trimaran':'788	',
'container ship, containership, container vessel':'789	',
'liner, ocean liner':'790	',
'aircraft carrier, carrier, flattop, attack aircraft carrier':'791	',
'submarine, pigboat, sub, U-boat':'792	',
'bobsled, bobsleigh, bob':'793	',
'dogsled, dog sled, dog sleigh':'794	',
'subway train':'795	',
'bullet train, bullet':'796	',
'trolleybus, trolley coach, trackless trolley':'797	',
'school bus':'798	',
'bassinet':'799	',
'crib, cot':'800	',
'four-poster':'801	',
'trundle bed, trundle, truckle bed, truckle':'802	',
'bookcase':'803	',
'china cabinet, china closet':'804	',
'medicine chest, medicine cabinet':'805	',
'lamp':'806	',
'file, file cabinet, filing cabinet':'807	',
'flat bench':'808	',
'park bench':'809	',
'pew, church bench':'810	',
'armchair':'811	',
'barber chair':'812	',
'folding chair':'813	',
'swivel chair':'814	',
'wheelchair':'815	',
'desk':'816	',
'table-tennis table, ping-pong table, pingpong table':'817	',
'dining table, board':'818	',
'entertainment center':'819	',
'wardrobe, closet, press':'820	',
'rug, carpet, carpeting':'821	',
'shower curtain':'822	',
'theater curtain, theatre curtain':'823	',
'newspaper, paper':'824	',
'magazine, mag':'825	',
'radio, wireless':'826	',
'television, television system':'827	',
'maze, labyrinth':'828	',
'triumphal arch':'829	',
'bridge, span':'830	',
'barn':'831	',
'greenhouse, nursery, glasshouse':'832	',
'library':'833	',
'garage':'834	',
'apiary, bee house':'835	',
'boathouse':'836	',
'church, church building':'837	',
'mosque':'838	',
'stupa, tope':'839	',
'planetarium':'840	',
'restaurant, eating house, eating place, eatery':'841	',
'skyscraper':'842	',
'cinema, movie theater, movie theatre, movie house, picture palace':'843	',
'home theater, home theatre':'844	',
'lumbermill, sawmill':'845	',
'coil, spiral, volute, whorl, helix':'846	',
'colonnade':'847	',
'obelisk':'848	',
'totem pole':'849	',
'castle':'850	',
'prison, prison house':'851	',
'grocery store, grocery, food market, market':'852	',
'barbershop':'853	',
'bookshop, bookstore, bookstall':'854	',
'butcher shop, meat market':'855	',
'confectionery, confectionary, candy store':'856	',
'shoe shop, shoe-shop, shoe store':'857	',
'tobacco shop, tobacconist shop, tobacconist':'858	',
'toyshop':'859	',
'fountain':'860	',
'house of cards, cardhouse, card-house, cardcastle':'861	',
'cliff dwelling':'862	',
'yurt':'863	',
'dock, dockage, docking facility':'864	',
'brass, memorial tablet, plaque':'865	',
'megalith, megalithic structure':'866	',
'bannister, banister, balustrade, balusters, handrail':'867	',
'breakwater, groin, groyne, mole, bulwark, seawall, jetty':'868	',
'dam, dike, dyke':'869	',
'chainlink fence':'870	',
'picket fence, paling':'871	',
'stone wall':'872	',
'grille, radiator grille':'873	',
'turnstile':'874	',
'tent, collapsible shelter':'875	',
'stadium, bowl, arena, sports stadium':'876	',
'honeycomb':'877	',
'buttress, buttressing':'878	',
'beacon, lighthouse, beacon light, pharos':'879	',
'silo':'880	',
'handkerchief, hankie, hanky, hankey':'881	',
'dishrag, dishcloth':'882	',
'paper towel':'883	',
'bath towel':'884	',
'bib':'885	',
'mask':'886	',
'shoji':'887	',
'sandal':'888	',
'running shoe':'889	',
'Loafer':'890	',
'boot':'891	',
'clog, geta, patten, sabot':'892	',
'sling, scarf bandage, triangular bandage':'893	',
'Band Aid':'894	',
'eyepatch, patch':'895	',
'quilt, comforter, comfort, puff':'896	',
'doormat, welcome mat':'897	',
'fancy dress, masquerade, masquerade costume':'898	',
'wig':'899	',
'collar':'900	',
'shin guard, shinpad':'901	',
'knee pad':'902	',
'apron':'903	',
'vestment':'904	',
'academic gown, academic robe, judge''s robe':'905	',
'bulletproof vest':'906	',
'swimming trunks, bathing trunks':'907	',
'maillot, tank suit':'908	',
'bikini, two-piece':'909	',
'suit, suit of clothes':'910	',
'jean, blue jean, denim':'911	',
'pajama, pyjama':'912	',
'short pants, shorts, trunks':'913	',
'feather boa, boa':'914	',
'headscarf':'915	',
'stole':'916	',
'bow tie, bow-tie, bowtie':'917	',
'Windsor tie':'918	',
'bolo tie, bolo, bola tie, bola':'919	',
'hoopskirt, crinoline':'920	',
'sarong':'921	',
'poncho':'922	',
'fur coat':'923	',
'oilskin, slicker':'924	',
'lab coat, laboratory coat':'925	',
'pullover, slipover':'926	',
'cardigan':'927	',
'kimono':'928	',
'abaya':'929	',
'bathrobe':'930	',
'polo shirt, sport shirt':'931	',
'jersey, T-shirt, tee shirt':'932	',
'brassiere, bra, bandeau':'933	',
'diaper, nappy, napkin':'934	',
'mitten':'935	',
'crash helmet':'936	',
'football helmet':'937	',
'hard hat, tin hat, safety hat':'938	',
'bathing cap, swimming cap':'939	',
'mortarboard':'940	',
'shower cap':'941	',
'garrison cap, overseas cap':'942	',
'bonnet, poke bonnet':'943	',
'bearskin, busby, shako':'944	',
'cowboy hat, ten-gallon hat':'945	',
'sombrero':'946	',
'turban':'947	',
'maillot':'948	',
'sock':'949	',
'Christmas stocking':'950	',
'military uniform':'951	',
'pajama, pyjama, pj''s, jammies':'952	',
'brace, suspender, gallus':'953	',
'jumper, pinafore, pinny':'954	',
'gown':'955	',
'pickelhaube':'956	',
'cannon':'957	',
'breastplate, aegis, egis':'958	',
'lens cap, lens cover':'959	',
'tile roof':'960	',
'dome':'961	',
'thatch, thatched roof':'962	',
'vault':'963	',
'Venetian blind':'964	',
'window shade':'965	',
'binder, ring-binder':'966	',
'lampshade, lamp shade':'967	',
'mosquito net':'968	',
'window screen':'969	',
'fire screen, fireguard':'970	',
'shield, buckler':'971	',
'cuirass':'972	',
'chain mail, ring mail, mail, chain armor, chain armour, ring armor, ring armour':'973	',
'gasmask, respirator, gas helmet':'974	',
'ski mask':'975	',
'holster':'976	',
'scabbard':'977	',
'birdhouse':'978	',
'bell cote, bell cot':'979	',
'umbrella':'980	',
'manhole cover':'981	',
'bottlecap':'982	',
'nipple':'983	',
'tumble-dryer, tumble drier':'984	',
'curling iron':'985	',
'iron, smoothing iron':'986	',
'espresso maker':'987	',
'hot plate, hotplate':'988	',
'ice maker':'989	',
'microwave, microwave oven':'990	',
'Dutch oven':'991	',
'rotisserie':'992	',
'electric range':'993	',
'Primus stove, Primus':'994	',
'toaster':'995	',
'waffle iron':'996	',
'vacuum, vacuum cleaner':'997	',
'dishwasher, dish washer, dishwashing machine':'998	',
'refrigerator, icebox':'999	',
'washer, automatic washer, washing machine' :'1000',
'entity':'1001',
'physical entity':'1002',
'matter':'1003',
'substance':'1004',
'food, nutrient':'1005',
'foodstuff, food product':'1006',
'starches':'1007',
'potato, white potato, Irish potato, murphy, spud, tater':'1008',
'ingredient, fixings':'1009',
'flavorer, flavourer, flavoring, flavouring, seasoner, seasoning':'1010',
'condiment':'1011',
'relish':'1012',
'olive':'1013',
'agent':'1014',
'drug':'1015',
'medicine, medication, medicament, medicinal drug':'1016',
'powder':'1017',
'solid':'1018',
'food, solid food':'1019',
'produce, green goods, green groceries, garden truck':'1020',
'edible fruit':'1021',
'apple':'1022',
'eating apple, dessert apple':'1023',
'berry':'1024',
'citrus, citrus fruit, citrous fruit':'1025',
'vegetable, veggie, veg':'1026',
'legume':'1027',
'bean, edible bean':'1028',
'common bean':'1029',
'pea':'1030',
'greens, green, leafy vegetable':'1031',
'salad green, salad greens':'1032',
'solanaceous vegetable':'1033',
'pepper':'1034',
'sweet pepper':'1035',
'hot pepper':'1036',
'chili, chili pepper, chilli, chilly, chile':'1037',
'tomato':'1038',
'root vegetable':'1039',
'cruciferous vegetable':'1040',
'cabbage, chou':'1041',
'squash':'1042',
'summer squash':'1043',
'winter squash':'1044',
'onion':'1045',
'causal agent, cause, causal agency':'1046',
'object, physical object':'1047',
'geological formation, formation':'1048',
'natural depression, depression':'1049',
'crater':'1050',
'natural elevation, elevation':'1051',
'mountain, mount':'1052',
'ridge':'1053',
'bar':'1054',
'reef':'1055',
'shore':'1056',
'spring, fountain, outflow, outpouring, natural spring':'1057',
'location':'1058',
'point':'1059',
'geographic point, geographical point':'1060',
'workplace, work':'1061',
'whole, unit':'1062',
'natural object':'1063',
'mechanism':'1064',
'barrier':'1065',
'plant part, plant structure':'1066',
'plant organ':'1067',
'reproductive structure':'1068',
'fruit':'1069',
'seed':'1070',
'edible seed':'1071',
'oilseed, oil-rich seed':'1072',
'grain, caryopsis':'1073',
'kernel':'1074',
'nut':'1075',
'edible nut':'1076',
'berry':'1077',
'drupe, stone fruit':'1078',
'drupelet':'1079',
'pome, false fruit':'1080',
'pod, seedpod':'1081',
'legume':'1082',
'living thing, animate thing':'1083',
'organism, being':'1084',
'plant, flora, plant life':'1085',
'vascular plant, tracheophyte':'1086',
'spermatophyte, phanerogam, seed plant':'1087',
'angiosperm, flowering plant':'1088',
'flower':'1089',
'anemone, windflower':'1090',
'columbine, aquilegia, aquilege':'1091',
'fig marigold, pebble plant':'1092',
'poppy':'1093',
'composite, composite plant':'1094',
'everlasting, everlasting flower':'1095',
'calendula':'1096',
'orchid, orchidaceous plant':'1097',
'orchis':'1098',
'helleborine':'1099',
'woody plant, ligneous plant':'1100',
'tree':'1101',
'anise tree':'1102',
'acacia':'1103',
'albizzia, albizia':'1104',
'beech, beech tree':'1105',
'southern beech, evergreen beech':'1106',
'oak, oak tree':'1107',
'birch, birch tree':'1108',
'ash, ash tree':'1109',
'fig tree':'1110',
'elm, elm tree':'1111',
'cassia':'1112',
'locust tree, locust':'1113',
'rosewood, rosewood tree':'1114',
'blackwood, blackwood tree':'1115',
'coffee, coffee tree':'1116',
'willow, willow tree':'1117',
'sallow':'1118',
'soapberry, soapberry tree':'1119',
'gymnospermous tree':'1120',
'conifer, coniferous tree':'1121',
'angiospermous tree, flowering tree':'1122',
'maple':'1123',
'fungus':'1124',
'basidiomycete, basidiomycetous fungi':'1125',
'mushroom':'1126',
'animal, animate being, beast, brute, creature, fauna':'1127',
'invertebrate':'1128',
'arthropod':'1129',
'arachnid, arachnoid':'1130',
'spider':'1131',
'acarine':'1132',
'crustacean':'1133',
'malacostracan crustacean':'1134',
'decapod crustacean, decapod':'1135',
'crab':'1136',
'lobster':'1137',
'true lobster':'1138',
'insect':'1139',
'beetle':'1140',
'dipterous insect, two-winged insects, dipteran, dipteron':'1141',
'hymenopterous insect, hymenopteran, hymenopteron, hymenopter':'1142',
'orthopterous insect, orthopteron, orthopteran':'1143',
'phasmid, phasmid insect':'1144',
'dictyopterous insect':'1145',
'homopterous insect, homopteran':'1146',
'ephemerid, ephemeropteran':'1147',
'neuropteron, neuropteran, neuropterous insect':'1148',
'odonate':'1149',
'lepidopterous insect, lepidopteron, lepidopteran':'1150',
'butterfly':'1151',
'danaid, danaid butterfly':'1152',
'pierid, pierid butterfly':'1153',
'coelenterate, cnidarian':'1154',
'anthozoan, actinozoan':'1155',
'worm':'1156',
'annelid, annelid worm, segmented worm':'1157',
'oligochaete, oligochaete worm':'1158',
'mollusk, mollusc, shellfish':'1159',
'gastropod, univalve':'1160',
'bivalve, pelecypod, lamellibranch':'1161',
'cephalopod, cephalopod mollusk':'1162',
'echinoderm':'1163',
'domestic animal, domesticated animal':'1164',
'domestic cat, house cat, Felis domesticus, Felis catus':'1165',
'dog, domestic dog, Canis familiaris':'1166',
'hunting dog':'1167',
'sporting dog, gun dog':'1168',
'pointer, Spanish pointer':'1169',
'setter':'1170',
'spaniel':'1171',
'retriever':'1172',
'terrier':'1173',
'bullterrier, bull terrier':'1174',
'hound, hound dog':'1175',
'poodle, poodle dog':'1176',
'working dog':'1177',
'shepherd dog, sheepdog, sheep dog':'1178',
'watchdog, guard dog':'1179',
'pinscher':'1180',
'mastiff':'1181',
'toy dog, toy':'1182',
'game':'1183',
'game bird':'1184',
'grouse':'1185',
'phasianid':'1186',
'racer':'1187',
'chordate':'1188',
'vertebrate, craniate':'1189',
'mammal, mammalian':'1190',
'placental, placental mammal, eutherian, eutherian mammal':'1191',
'lagomorph, gnawing mammal':'1192',
'leporid, leporid mammal':'1193',
'rabbit, coney, cony':'1194',
'primate':'1195',
'lemur':'1196',
'ape':'1197',
'anthropoid ape':'1198',
'great ape, pongid':'1199',
'lesser ape':'1200',
'monkey':'1201',
'New World monkey, platyrrhine, platyrrhinian':'1202',
'Old World monkey, catarrhine':'1203',
'proboscidean, proboscidian':'1204',
'elephant':'1205',
'carnivore':'1206',
'bear':'1207',
'musteline mammal, mustelid, musteline':'1208',
'procyonid':'1209',
'viverrine, viverrine mammal':'1210',
'canine, canid':'1211',
'wild dog':'1212',
'fox':'1213',
'wolf':'1214',
'feline, felid':'1215',
'cat, true cat':'1216',
'wildcat':'1217',
'big cat, cat':'1218',
'pachyderm':'1219',
'bird':'1220',
'gallinaceous bird, gallinacean':'1221',
'reptile, reptilian':'1222',
'anapsid, anapsid reptile':'1223',
'chelonian, chelonian reptile':'1224',
'turtle':'1225',
'sea turtle, marine turtle':'1226',
'diapsid, diapsid reptile':'1227',
'saurian':'1228',
'lizard':'1229',
'gecko':'1230',
'iguanid, iguanid lizard':'1231',
'teiid lizard, teiid':'1232',
'agamid, agamid lizard':'1233',
'anguid lizard':'1234',
'venomous lizard':'1235',
'lacertid lizard, lacertid':'1236',
'chameleon, chamaeleon':'1237',
'monitor, monitor lizard, varan':'1238',
'snake, serpent, ophidian':'1239',
'colubrid snake, colubrid':'1240',
'constrictor':'1241',
'boa':'1242',
'elapid, elapid snake':'1243',
'cobra':'1244',
'mamba':'1245',
'black mamba, Dendroaspis augusticeps':'1246',
'viper':'1247',
'amphibian':'1248',
'frog, toad, toad frog, anuran, batrachian, salientian':'1249',
'true frog, ranid':'1250',
'salamander':'1251',
'newt, triton':'1252',
'ambystomid, ambystomid salamander':'1253',
'aquatic vertebrate':'1254',
'fish':'1255',
'cartilaginous fish, chondrichthian':'1256',
'elasmobranch, selachian':'1257',
'shark':'1258',
'mackerel shark':'1259',
'requiem shark':'1260',
'ray':'1261',
'food fish':'1262',
'salmon':'1263',
'trout':'1264',
'sea bass':'1265',
'bony fish':'1266',
'teleost fish, teleost, teleostan':'1267',
'soft-finned fish, malacopterygian':'1268',
'salmonid':'1269',
'spiny-finned fish, acanthopterygian':'1270',
'percoid fish, percoid, percoidean':'1271',
'serranid fish, serranid':'1272',
'ganoid, ganoid fish':'1273',
'artifact, artefact':'1274',
'instrumentality, instrumentation':'1275',
'device':'1276',
'musical instrument, instrument':'1277',
'bass':'1278',
'bass horn, sousaphone, tuba':'1279',
'keyboard instrument':'1280',
'piano, pianoforte, forte-piano':'1281',
'percussion instrument, percussive instrument':'1282',
'stringed instrument':'1283',
'bowed stringed instrument, string':'1284',
'chordophone':'1285',
'guitar':'1286',
'wind instrument, wind':'1287',
'brass, brass instrument':'1288',
'free-reed instrument':'1289',
'pipe':'1290',
'woodwind, woodwind instrument, wood':'1291',
'beating-reed instrument, reed instrument, reed':'1292',
'double-reed instrument, double reed':'1293',
'single-reed instrument, single-reed woodwind':'1294',
'acoustic device':'1295',
'applicator, applier':'1296',
'blower':'1297',
'breathing device, breathing apparatus, breathing machine, ventilator':'1298',
'electrical device':'1299',
'transducer':'1300',
'electro-acoustic transducer':'1301',
'electronic device':'1302',
'fan':'1303',
'instrument':'1304',
'instrument of execution':'1305',
'measuring instrument, measuring system, measuring device':'1306',
'measuring stick, measure, measuring rod':'1307',
'meter':'1308',
'timepiece, timekeeper, horologe':'1309',
'clock':'1310',
'sandglass':'1311',
'medical instrument':'1312',
'optical instrument':'1313',
'scientific instrument':'1314',
'magnifier':'1315',
'microscope':'1316',
'light microscope':'1317',
'telescope, scope':'1318',
'astronomical telescope':'1319',
'weapon, arm, weapon system':'1320',
'gun':'1321',
'firearm, piece, small-arm':'1322',
'autoloader, self-loader':'1323',
'automatic firearm, automatic gun, automatic weapon':'1324',
'pistol, handgun, side arm, shooting iron':'1325',
'keyboard':'1326',
'lifting device':'1327',
'machine':'1328',
'power tool':'1329',
'power saw, saw, sawing machine':'1330',
'calculator, calculating machine':'1331',
'computer, computing machine, computing device, data processor, electronic computer, information processing system':'1332',
'digital computer':'1333',
'personal computer, PC, microcomputer':'1334',
'portable computer':'1335',
'farm machine':'1336',
'printer, printing machine':'1337',
'slot machine, coin machine':'1338',
'textile machine':'1339',
'mechanism':'1340',
'control, controller':'1341',
'mechanical device':'1342',
'pump':'1343',
'ride':'1344',
'rotating mechanism':'1345',
'memory device, storage device':'1346',
'magnetic disk, magnetic disc, disk, disc':'1347',
'memory, computer memory, storage, computer storage, store, memory board':'1348',
'non-volatile storage, nonvolatile storage':'1349',
'reflector':'1350',
'mirror':'1351',
'restraint, constraint':'1352',
'fastener, fastening, holdfast, fixing':'1353',
'clip':'1354',
'lock':'1355',
'safety belt, life belt, safety harness':'1356',
'signaling device':'1357',
'source of illumination':'1358',
'lamp':'1359',
'lantern':'1360',
'trap':'1361',
'web, entanglement':'1362',
'implement':'1363',
'tool':'1364',
'cutting implement':'1365',
'cutter, cutlery, cutting tool':'1366',
'edge tool':'1367',
'knife':'1368',
'razor':'1369',
'garden tool, lawn tool':'1370',
'hand tool':'1371',
'opener':'1372',
'bottle opener':'1373',
'wrench, spanner':'1374',
'utensil':'1375',
'kitchen utensil':'1376',
'cooking utensil, cookware':'1377',
'pan, cooking pan':'1378',
'pot':'1379',
'turner, food turner':'1380',
'mixer':'1381',
'cleaning implement, cleaning device, cleaning equipment':'1382',
'brush':'1383',
'eraser':'1384',
'sharpener':'1385',
'rod':'1386',
'writing implement':'1387',
'pen':'1388',
'beater':'1389',
'stick':'1390',
'staff':'1391',
'bar':'1392',
'lever':'1393',
'compound lever':'1394',
'container':'1395',
'wheeled vehicle':'1396',
'bicycle, bike, wheel, cycle':'1397',
'car, railcar, railway car, railroad car':'1398',
'handcart, pushcart, cart, go-cart':'1399',
'self-propelled vehicle':'1400',
'armored vehicle, armoured vehicle':'1401',
'locomotive, engine, locomotive engine, railway locomotive':'1402',
'motor vehicle, automotive vehicle':'1403',
'car, auto, automobile, machine, motorcar':'1404',
'motorcycle, bike':'1405',
'minibike, motorbike':'1406',
'truck, motortruck':'1407',
'van':'1408',
'passenger van':'1409',
'tracked vehicle':'1410',
'wagon, waggon':'1411',
'cart':'1412',
'basket, handbasket':'1413',
'bag':'1414',
'bin':'1415',
'shaker':'1416',
'vessel':'1417',
'basin':'1418',
'jar':'1419',
'bottle':'1420',
'flask':'1421',
'tank, storage tank':'1422',
'reservoir':'1423',
'cistern':'1424',
'drinking vessel':'1425',
'glass, drinking glass':'1426',
'box':'1427',
'strongbox, deedbox':'1428',
'measure':'1429',
'case':'1430',
'baggage, luggage':'1431',
'equipment':'1432',
'sports equipment':'1433',
'golf equipment':'1434',
'baseball equipment':'1435',
'gymnastic apparatus, exerciser':'1436',
'basketball equipment':'1437',
'croquet equipment':'1438',
'weight, free weight, exercising weight':'1439',
'skate':'1440',
'game equipment':'1441',
'game':'1442',
'puzzle':'1443',
'bowling equipment':'1444',
'man, piece':'1445',
'ball':'1446',
'photographic equipment':'1447',
'camera, photographic camera':'1448',
'gear, paraphernalia, appurtenance':'1449',
'kit, outfit':'1450',
'rig':'1451',
'drill rig, drilling rig, oilrig, oil rig':'1452',
'electronic equipment':'1453',
'audio system, sound system':'1454',
'reproducer':'1455',
'stereo, stereophony, stereo system, stereophonic system':'1456',
'television equipment, video equipment':'1457',
'television camera, tv camera, camera':'1458',
'peripheral, computer peripheral, peripheral device':'1459',
'data input device, input device':'1460',
'telephone, phone, telephone set':'1461',
'radiotelephone, radiophone, wireless telephone':'1462',
'apparatus, setup':'1463',
'duplicator, copier':'1464',
'pendulum':'1465',
'rescue equipment':'1466',
'ceramic':'1467',
'toiletry, toilet articles':'1468',
'cosmetic':'1469',
'makeup, make-up, war paint':'1470',
'conveyance, transport':'1471',
'vehicle':'1472',
'craft':'1473',
'aircraft':'1474',
'heavier-than-air craft':'1475',
'airplane, aeroplane, plane':'1476',
'lighter-than-air craft':'1477',
'vessel, watercraft':'1478',
'boat':'1479',
'motorboat, powerboat':'1480',
'sea boat':'1481',
'small boat':'1482',
'sailing vessel, sailing ship':'1483',
'sailboat, sailing boat':'1484',
'ship':'1485',
'cargo ship, cargo vessel':'1486',
'passenger ship':'1487',
'warship, war vessel, combat ship':'1488',
'submersible, submersible warship':'1489',
'military vehicle':'1490',
'rocket, projectile':'1491',
'sled, sledge, sleigh':'1492',
'public transport':'1493',
'train, railroad train':'1494',
'passenger train':'1495',
'bus, autobus, coach, charabanc, double-decker, jitney, motorbus, motorcoach, omnibus, passenger vehicle':'1496',
'furnishing':'1497',
'furniture, piece of furniture, article of furniture':'1498',
'baby bed, baby''s bed':'1499',
'bedroom furniture':'1500',
'bed':'1501',
'cabinet':'1502',
'office furniture':'1503',
'seat':'1504',
'bench':'1505',
'chair':'1506',
'table':'1507',
'table':'1508',
'wall unit':'1509',
'curtain, drape, drapery, mantle, pall':'1510',
'medium':'1511',
'print media':'1512',
'press, public press':'1513',
'system':'1514',
'communication system':'1515',
'telecommunication system, telecom system, telecommunication equipment, telecom equipment':'1516',
'structure, construction':'1517',
'arch':'1518',
'building, edifice':'1519',
'farm building':'1520',
'outbuilding':'1521',
'shed':'1522',
'place of worship, house of prayer, house of God, house of worship':'1523',
'shrine':'1524',
'theater, theatre, house':'1525',
'building complex, complex':'1526',
'plant, works, industrial plant':'1527',
'factory, mill, manufacturing plant, manufactory':'1528',
'column, pillar':'1529',
'defensive structure, defense, defence':'1530',
'fortification, munition':'1531',
'establishment':'1532',
'institution':'1533',
'penal institution, penal facility':'1534',
'correctional institution':'1535',
'place of business, business establishment':'1536',
'mercantile establishment, retail store, sales outlet, outlet':'1537',
'marketplace, market place, mart, market':'1538',
'shop, store':'1539',
'housing, lodging, living accommodations':'1540',
'dwelling, home, domicile, abode, habitation, dwelling house':'1541',
'landing, landing place':'1542',
'memorial, monument':'1543',
'obstruction, obstructor, obstructer, impediment, impedimenta':'1544',
'barrier':'1545',
'fence, fencing':'1546',
'grate, grating':'1547',
'movable barrier':'1548',
'gate':'1549',
'shelter':'1550',
'supporting structure':'1551',
'framework':'1552',
'support':'1553',
'tower':'1554',
'creation':'1555',
'product, production':'1556',
'work, piece of work':'1557',
'publication':'1558',
'fabric, cloth, material, textile':'1559',
'piece of cloth, piece of material':'1560',
'towel':'1561',
'covering':'1562',
'screen, cover, covert, concealment':'1563',
'footwear, footgear':'1564',
'shoe':'1565',
'coating, coat':'1566',
'enamel':'1567',
'cloth covering':'1568',
'dressing, medical dressing':'1569',
'bandage, patch':'1570',
'adhesive bandage':'1571',
'bedclothes, bed clothing, bedding':'1572',
'floor cover, floor covering':'1573',
'mat':'1574',
'clothing, article of clothing, vesture, wear, wearable, habiliment':'1575',
'attire, garb, dress':'1576',
'costume':'1577',
'disguise':'1578',
'hairpiece, false hair, postiche':'1579',
'neckpiece':'1580',
'protective garment':'1581',
'accessory, accoutrement, accouterment':'1582',
'belt':'1583',
'outerwear, overclothes':'1584',
'gown, robe':'1585',
'garment':'1586',
'vest, waistcoat':'1587',
'swimsuit, swimwear, bathing suit, swimming costume, bathing costume':'1588',
'trouser, pant':'1589',
'scarf':'1590',
'kerchief':'1591',
'neckwear':'1592',
'necktie, tie':'1593',
'skirt':'1594',
'overgarment, outer garment':'1595',
'cloak':'1596',
'coat':'1597',
'raincoat, waterproof':'1598',
'macintosh, mackintosh, mac, mack':'1599',
'sweater, jumper':'1600',
'robe':'1601',
'shirt':'1602',
'undergarment, unmentionable':'1603',
'handwear, hand wear':'1604',
'glove':'1605',
'headdress, headgear':'1606',
'helmet':'1607',
'cap':'1608',
'hat, chapeau, lid':'1609',
'footwear':'1610',
'hosiery, hose':'1611',
'tights, leotards':'1612',
'stocking':'1613',
'uniform':'1614',
'nightwear, sleepwear, nightclothes':'1615',
'apparel, wearing apparel, dress, clothes':'1616',
'workwear':'1617',
'man''s clothing':'1618',
'woman''s clothing':'1619',
'dress, frock':'1620',
'protective covering, protective cover, protection':'1621',
'shield':'1622',
'plate, scale, shell':'1623',
'armor plate, armour plate, armor plating, plate armor, plate armour':'1624',
'helmet':'1625',
'cap':'1626',
'roof':'1627',
'blind, screen':'1628',
'window blind':'1629',
'shade':'1630',
'screen':'1631',
'armor, armour':'1632',
'body armor, body armour, suit of armor, suit of armour, coat of mail, cataphract':'1633',
'mask':'1634',
'face mask':'1635',
'sheath':'1636',
'shelter':'1637',
'canopy':'1638',
'top, cover':'1639',
'cap':'1640',
'commodity, trade good, good':'1641',
'consumer goods':'1642',
'durables, durable goods, consumer durables':'1643',
'appliance':'1644',
'dryer, drier':'1645',
'clothes dryer, clothes drier':'1646',
'home appliance, household appliance':'1647',
'kitchen appliance':'1648',
'coffee maker':'1649',
'oven':'1650',
'stove, kitchen stove, range, kitchen range, cooking stove':'1651',
'white goods':'1652',
'drygoods, soft goods':'1653',
'white goods, household linen':'1654',
'linen':'1655',
'bath linen':'1656',
'excavation':'1657',
'pool':'1658',
'building material':'1659',
'decoration, ornament, ornamentation':'1660',
'design, pattern, figure':'1661',
'emblem':'1662',
'part, portion':'1663',
'piece':'1664',
'component, constituent, element':'1665',
'hardware, computer hardware':'1666',
'abstraction, abstract entity':'1667',
'group, grouping':'1668',
'social group':'1669',
'organization, organisation':'1670',
'enterprise':'1671',
'business, concern, business concern, business organization, business organisation':'1672',
'carrier, common carrier':'1673',
'line':'1674',
'railway, railroad, railroad line, railway line, railway system':'1675',
'elevated railway, elevated railroad, elevated, el, overhead railway'  :'1676'                                                                                                                          

}

data = {}
average_accuracies = []
accuracies = []

for model_version in tqdm(range(8)):
    model_name = f'efficientnet-b{model_version}'
    model = EfficientNet.from_pretrained(model_name)
    efficientnet = model.eval().to(device)

    accuracy = []
    results = np.zeros((len(ground_truth_labels), 5))
    uris = []
    total_files = 0
    batch_size = 16

    file_names = sorted(os.listdir(root_dir))  # Sort in root_dir
    for file_name in file_names:
        file_path = os.path.join(root_dir, file_name)
        if os.path.isfile(file_path):
            total_files += 1
            if total_files > num_test_files:
                break
            uris.append(file_path)

    # Convert images to RGB format if necessary
    for i in range(len(uris)):
        image = Image.open(uris[i])
        if image.mode != 'RGB':
            print(i)
            image = image.convert('RGB')
            image.save(uris[i])  # Overwrite the image with RGB format

    with torch.no_grad():
        count2 = 0
        for i in range(0, len(uris), batch_size):
            batch_uris = uris[i:i+batch_size]
            batch = torch.cat([utils.prepare_input_from_uri(uri) for uri in batch_uris]).to(device)
            output = torch.nn.functional.softmax(efficientnet(batch), dim=1)
            batch_results = utils.pick_n_best(predictions=output, n=5)
            k = 0
            for result in batch_results:
                inter_result = []
                for j in range(5):
                    prediction_str = result[j][0]
                    mapped_prediction = mapping_dict.get(prediction_str, 0)  # Assign 0 if prediction is not in mapping_dict
                    if isinstance(mapped_prediction, int):
                        mapped_prediction = str(mapped_prediction)
                    mapped_prediction = mapped_prediction.replace('\t', '').strip()
                    inter_result.append(mapped_prediction)
                    #results[k][j] = mapped_prediction    
                results[count2] = inter_result
                count2 += 1

    count = 0
    for i in range(len(results)):
        for j in range(5):
            results[i][j] = int(results[i][j])
        if ground_truth_labels[i] in results[i]:
            count += 1

    accuracy = count / (len(results)-1) * 100
    accuracies.append(accuracy)
     
np.savetxt("accuracies_last.txt",accuracies,delimiter=", ")
model_versions = ['efficientnet-b0', 'efficientnet-b1', 'efficientnet-b2', 'efficientnet-b3', 'efficientnet-b4',
                  'efficientnet-b5', 'efficientnet-b6', 'efficientnet-b7']

plt.figure(figsize=(6, 4))
plt.plot(model_versions, accuracies, 'ro-')
plt.xlabel('Model Versions', fontsize=12)
plt.ylabel('Average Accuracy (%)', fontsize=12)
plt.title('Model Versions vs Average Accuracy', fontsize=14)
plt.xticks(rotation=45, fontsize=10)
plt.yticks(fontsize=10)
plt.tight_layout()
plt.savefig('eff_compare_last.png')
plt.show()
